name: Validation Tests

on: [push, pull_request]

jobs:

  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      with:
          submodules: true

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: 8.2

    - name: Install latest PHPUnit
      run: wget https://phar.phpunit.de/phpunit-9.phar

# deactivated    - name: Run Tests
# deactivated      run: phpdbg -qrr phpunit-9.phar tests
